<rootmenu>
    <menu>
        <name>dashboard</name>
        <is_all>1</is_all>
    </menu>
    <menu>
        <name>login</name>
        <is_all>1</is_all>
    </menu>
    <menu>
        <name>myaccount</name>
        <is_all>1</is_all>
    </menu>
    <menu>
        <name>search</name>
        <is_all>1</is_all>
    </menu>
    <menu>
        <name>config_general</name>
        <is_admin>1</is_admin>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>shipping_fee</name></act>
    </menu>
    <menu>
        <name>email</name>
        <is_admin>1</is_admin>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>
    <menu>
        <name>emailtpl</name>
        <is_admin>1</is_admin>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>
    <menu>
        <name>user</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>config_commission</name></act>
        <act><name>work_schedule</name></act>
        <act><name>create_shift_work</name></act>
        <act><name>all_branches</name></act>
    </menu>
    <menu>
        <name>user_group</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
    </menu>
    <menu>
        <name>config</name>
        <is_root>1</is_root>
    </menu>
    <menu>
        <name>logs</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>search</name></act>
    </menu>
    <!--<menu>
        <name>phpinfo</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
    </menu>
    <menu>
        <name>optimize</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>exe</name></act>
    </menu>-->
    <menu>
        <name>comment</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>hide</name></act>
        <act><name>approve</name></act>
    </menu>
    <menu>
        <name>accounts</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>
    <menu>
        <name>accounts_type</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>
    <menu>
        <name>store</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
        <act><name>transfer</name></act>
    </menu>
    <menu>
        <name>manufacture</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>deleteall</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>
    <menu>
        <name>product_group</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
        <act><name>import</name></act>
        <act><name>export</name></act>
    </menu>
    <menu>
        <name>product</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>hide_all</name></act>
        <act><name>arrange</name></act>
        <act><name>get_barcode_info</name></act>
        <act><name>preview_barcode</name></act>
        <act><name>import</name></act>
        <act><name>export</name></act>
    </menu>

    <menu>
        <name>attribute</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>

    <menu>
        <name>assets</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>get_barcode_info</name></act>
        <act><name>preview_barcode</name></act>
        <act><name>print_to_excel</name></act>
        <act><name>all_branches</name></act>
    </menu>
     <menu>
        <name>config_price</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>
    <menu>
        <name>inventory</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>approve</name></act>
    </menu>
    <menu>
        <name>customer</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>

    <menu>
        <name>group_customer</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>

    <menu>
        <name>order</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
        <act><name>renew</name></act>
        <act><name>rating</name></act>
        <act><name>all_branches</name></act>
    </menu>
    <menu>
        <name>transactions</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>preview</name></act>
        <act><name>print</name></act>
        <act><name>send</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
        <act><name>all_branches</name></act>
    </menu>

    <menu>
        <name>supplier</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>
    <menu>
        <name>partner_delivery</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>

    <menu>
        <name>shipment</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>

    <menu>
        <name>store_request</name>
        <is_root>1</is_root>

        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>del</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
        <act><name>approve</name></act>
        <act><name>preview</name></act>
        <act><name>cancel</name></act>

        <act><name>read_request</name></act>
        <act><name>add_request</name></act>
        <act><name>edit_request</name></act>
        <act><name>delete_request</name></act>
        <act><name>search_request</name></act>
        <act><name>approve_request</name></act>
        <act><name>cancel_request</name></act>

        <act><name>read_request_ei</name></act>
        <act><name>add_request_ei</name></act>
        <act><name>edit_request_ei</name></act>
        <act><name>delete_request_ei</name></act>
        <act><name>search_request_ei</name></act>
        <act><name>approve_request_ei</name></act>
        <act><name>cancel_request_ei</name></act>

        <act><name>read_request_eis</name></act>
        <act><name>add_request_eis</name></act>
    </menu>

    <menu>
        <name>transaction_terms</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>

    <menu>
        <name>returns</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>approve</name></act>
        <act><name>cancel</name></act>
    </menu>

    <menu>
        <name>news</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>approve</name></act>
    </menu>

    <menu>
        <name>config_parent_news</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>
     <menu>
        <name>videos</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>approve</name></act>
    </menu>
    <menu>
        <name>config_parent_videos</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>
    <menu>
        <name>giftcards</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>

    <menu>
        <name>coupons</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>
    <menu>
        <name>sms</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>
    <menu>
        <name>smstpl</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <!--<act><name>delete</name></act>-->
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>
    <menu>
        <name>config_gallery</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>

    <menu>
        <name>pages</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>

    <menu>
        <name>position</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>

    <menu>
        <name>logos</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>

    <menu>
        <name>logo_positions</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>

    <menu>
        <name>newsletter</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>send_mail</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>
    <menu>
        <name>addons</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
    </menu>

    <menu>
        <name>gallery</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>arrange</name></act>
    </menu>

    <menu>
        <name>report</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>sales</name></act>
        <act><name>order</name></act>
        <act><name>product</name></act>
        <act><name>customer</name></act>
        <act><name>finance</name></act>
        <act><name>inventory</name></act>
        <act><name>assets</name></act>
    </menu>

    <menu>
        <name>redeem</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
    </menu>

    <menu>
        <name>seo</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>

    <menu>
        <name>discount</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>import</name></act>
        <act><name>export</name></act>
    </menu>

    <menu>
        <name>discount_items</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>import</name></act>
        <act><name>export</name></act>
    </menu>

	<menu>
        <name>facebook</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
    </menu>

    <menu>
        <name>embed</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>import</name></act>
        <act><name>export</name></act>
    </menu>
    <menu>
        <name>interface</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
    </menu>

    <menu>
        <name>contact</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>

    <menu>
        <name>rating</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>import</name></act>
        <act><name>export</name></act>
    </menu>

    <menu>
        <name>service</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>hide_all</name></act>
        <act><name>arrange</name></act>
        <act><name>get_barcode_info</name></act>
        <act><name>preview_barcode</name></act>
        <act><name>import</name></act>
        <act><name>export</name></act>
    </menu>

    <menu>
        <name>staff</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>
    <menu>
        <name>custom_status</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>
    <menu>
        <name>work_schedule</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>
    <menu>
        <name>shift_work</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>

    <menu>
        <name>variants</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
    </menu>

    <menu>
        <name>price</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>add</name></act>
        <act><name>edit</name></act>
        <act><name>delete</name></act>
        <act><name>search</name></act>
        <act><name>set_default</name></act>
    </menu>

    <menu>
        <name>abandoned</name>
        <is_root>1</is_root>
        <act><name>read</name></act>
        <act><name>delete</name></act>
    </menu>
</rootmenu>